name: Go

on:
  push:
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go
    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install protoc
      run: ./scripts/protoc-install.sh 3.11.4
        
    - name: Get dependencies
      run: make deps

    - name: Build
      run: make

    - name: Build C lib
      run: make clib
    
    - name: Test
      run: make test

    - name: Store C library
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.os }}-clib
        path: binding
